apiVersion: apps/v1
kind: Deployment
metadata:
  name: adot-collector
  namespace: amazon-cloudwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adot-collector
  template:
    metadata:
      labels:
        app: adot-collector
    spec:
      serviceAccountName: adot-collector
      containers:
        - name: otel-collector
          image: public.ecr.aws/aws-observability/aws-otel-collector:latest
          command:
            - "/awscollector"
            - "--config=/etc/otel-config/adot-config.yaml"
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
            requests:
              cpu: 256m
              memory: 256Mi
          env:
            - name: AWS_REGION
              value: ap-south-1
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel-config
      volumes:
        - name: otel-config
          configMap:
            name: adot-collector-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: amazon-cloudwatch
data:
  adot-config.yaml: |
    receivers:
      awscontainerinsightreceiver:
        collection_interval: 60s
        container_orchestrator: eks
        host_root: ""

    exporters:
      awsemf:
        region: ap-south-1
        namespace: ContainerInsights
        log_group_name: /aws/containerinsights/YOUR-CLUSTER-NAME/performance
        resource_to_telemetry_conversion:
          enabled: true

    service:
      pipelines:
        metrics:
          receivers: [awscontainerinsightreceiver]
          exporters: [awsemf]
