apiVersion: apps/v1
kind: Deployment
metadata:
  name: formfillapp
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: formfillapp
  template:
    metadata:
      labels:
        app: formfillapp
    spec:
      containers:
        - name: c01
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 5
