image:
  repository: 842746302447.dkr.ecr.ap-south-1.amazonaws.com/formfill-app
  tag: latest

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
